### ISSUE TITLE
New Uniswap connector

### ISSUE THREAD

**Issue by KaymasJain** [Instadapp/dsa-connectors-old#31]
Take slippage in 2 ways for deposits.

Current version:-
tokenA has fixed amount but tokenB is variable according to price change in the meantime.

New version:- (Use try catch, no unitAmt needed only slippage)
- First try with tokenA fixed amount and tokenB variable. Let's take 1 ETH | 500 DAI with a slippage of 1%. So that makes the range at 1 ETH & 495 to 505 DAI. Now if ETH price increase meaning DAI between 500 to 505. The user might have a shortage of DAI in this scenario. If user has DAI shortage than next one.
- Take tokenB as fixed at 500 DAI & ETH will range from 0.99 to 1.01. So if above fails it'll succeed on this for sure.

**Comment by KaymasJain** [comment]
Also, I'm thinking to have one more functionality of add single token. We'll swap into subsequent other but this won't go well with big deposit. What would you suggest?

**Comment by KaymasJain** [comment]
@thrilok209 @mubaris

**Comment by mubaris** [comment]
This makes sense, for most pairs first step won't fail.

As for single side liquidity is also possible irrespective of the amount. We can always calculate the amount of token B given the amount of token A, if we only consider Pool A-B.

For example Alpha Finance does this. They calculate the pool parameters after you do the swap on the same pool, then you can get amount of token B if you only provide token A. You can see this [here](https://github.com/AlphaFinanceLab/alphahomora/blob/master/contracts/5/StrategyAddETHOnly.sol#L37-L56)
